name: PR Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - reopened
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout
        uses: actions/checkout@master

      - name: Enable node
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build packages
        run: yarn build

      - name: Lint types and code
        run: yarn lint

      - name: Run tests
        run: yarn test:ci

  release:
    name: Release Snapshot (if labelled)
    runs-on: ubuntu-latest
    if: contains( github.event.pull_request.labels.*.name, 'release:canary' )
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Yarn cache path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout
        uses: actions/checkout@master

      - name: Enable node
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: Load Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Publish Canary
        id: changesets
        uses: changesets/action@master
        with:
          publish: yarn release:canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Compute new packages info
        id: packagesData
        if: success() && steps.changesets.outputs.published == 'true'
        run: |
          echo "::set-output name=count::$(echo ${{toJson(steps.changesets.outputs.publishedPackages)}} | jq '. | length')"
          echo "::set-output name=packageList::$(echo ${{toJson(steps.changesets.outputs.publishedPackages)}} | jq 'reduce .[] as $item (""; . + "#### \($item.name)@\($item.version)\n```\nnpm install \($item.name)@canary\n```\n")')

      - name: Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: success() && steps.changesets.outputs.published == 'true'
        with:
          header: "canary-release"
          message: |
            ### :package: Canary Packages Published

            Latest commit: ${{ github.event.pull_request.head.sha }}

            <details>
               <summary>Published ${{ steps.packagesData.outputs.count }} packages</summary>
              ${{ fromJSON(steps.packagesData.outputs.packageList) }}
            </details>
