name: Publish to NPM

on:
  push:
    paths:
      - ".changeset/**"
      - "tooling/**"
      - "packages/**"
    branches:
      - main
      - next

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - id: yarn-cache
        name: Get Yarn cache path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - uses: actions/cache@v2
        name: Load Yarn cache
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile && yarn bootstrap

      - name: Setup CI Git User
        run: |
          git config --global user.email "joseshegs@gmail.com"
          git config --global user.name "Sage"

      - name: Build packages
        run: yarn build

      - name: Build CRA templates
        run: yarn build:templates ../cra-templates

      - name: Run tests
        run: yarn test:ci

      - name: Publish packages
        uses: changesets/action@master
        with:
          publish: yarn release
          commit: "chore(release): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Post updates to Discord announcement channel
        run: yarn discord

      - name: Generate changelog
        run: yarn changelog:write

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git diff --staged --quiet || git commit -m "docs: update changelog"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          delete-branch: true
          title: "docs: update changelog"
          branch: docs/changelog
